[package]
name = "ruste"
version = "0.1.0"
authors = ["youness_kafia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daggy = "0.6.0"